### ISSUE TITLE
Error: no matching decryption secret

### ISSUE THREAD

**Issue by robinhodemorais** [msgbyte/tianji#110]
what could this error be?

`[auth][error] JWTSessionError: Read more at https://errors.authjs.dev#jwtsessionerror

[auth][cause]: Error: no matching decryption secret

    at jwtDecrypt.clockTolerance (file:///app/tianji/node_modules/.pnpm/@auth+core@0.34.1_nodemailer@6.9.8/node_modules/@auth/core/jwt.js:76:15)

    at async flattenedDecrypt (file:///app/tianji/node_modules/.pnpm/jose@5.6.3/node_modules/jose/dist/node/esm/jwe/flattened/decrypt.js:92:15)

    at async compactDecrypt (file:///app/tianji/node_modules/.pnpm/jose@5.6.3/node_modules/jose/dist/node/esm/jwe/compact/decrypt.js:15:23)

    at async jwtDecrypt (file:///app/tianji/node_modules/.pnpm/jose@5.6.3/node_modules/jose/dist/node/esm/jwt/decrypt.js:5:23)

    at async Object.decode (file:///app/tianji/node_modules/.pnpm/@auth+core@0.34.1_nodemailer@6.9.8/node_modules/@auth/core/jwt.js:67:25)

    at async Module.session (file:///app/tianji/node_modules/.pnpm/@auth+core@0.34.1_nodemailer@6.9.8/node_modules/@auth/core/lib/actions/session.js:17:29)

    at async AuthInternal (file:///app/tianji/node_modules/.pnpm/@auth+core@0.34.1_nodemailer@6.9.8/node_modules/@auth/core/lib/index.js:35:24)

    at async Auth (file:///app/tianji/node_modules/.pnpm/@auth+core@0.34.1_nodemailer@6.9.8/node_modules/@auth/core/index.js:109:34)

    at async getAuthSession (file:///app/tianji/src/server/dist/src/server/model/auth.js:118:22)

    at async Array.<anonymous> (file:///app/tianji/src/server/dist/src/server/ws/index.js:30:33)

[auth][details]: {}

[Socket] Authenticated throw error: Error: Can not get user info.

    at Array.<anonymous> (file:///app/tianji/src/server/dist/src/server/ws/index.js:32:27)`

**Comment by moonrailgun** [comment]
looks weird. 
did you config any `JWT_SECRET` or `AUTH_SECRET`?
